// <auto-generated />
using KindergartenArtScoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KindergartenArtScoreAPI.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250309172842_RenameColumns")]
    partial class RenameColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("KindergartenArtScoreAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("art_score")
                        .HasAnnotation("Relational:JsonPropertyName", "art_score");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("class_name")
                        .HasAnnotation("Relational:JsonPropertyName", "class_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtScore = 92,
                            ClassName = "香蕉",
                            Name = "瑾瑜 羅"
                        },
                        new
                        {
                            Id = 2,
                            ArtScore = 79,
                            ClassName = "草莓",
                            Name = "燁磊 尹"
                        },
                        new
                        {
                            Id = 3,
                            ArtScore = 3,
                            ClassName = "香蕉",
                            Name = "天宇 蘇"
                        },
                        new
                        {
                            Id = 4,
                            ArtScore = 57,
                            ClassName = "香蕉",
                            Name = "子軒 董"
                        },
                        new
                        {
                            Id = 5,
                            ArtScore = 29,
                            ClassName = "草莓",
                            Name = "智宸 袁"
                        },
                        new
                        {
                            Id = 6,
                            ArtScore = 23,
                            ClassName = "草莓",
                            Name = "志澤 孔"
                        },
                        new
                        {
                            Id = 7,
                            ArtScore = 46,
                            ClassName = "香蕉",
                            Name = "鈺軒 盧"
                        },
                        new
                        {
                            Id = 8,
                            ArtScore = 24,
                            ClassName = "蘋果",
                            Name = "昊強 何"
                        },
                        new
                        {
                            Id = 9,
                            ArtScore = 67,
                            ClassName = "草莓",
                            Name = "智宸 董"
                        },
                        new
                        {
                            Id = 10,
                            ArtScore = 54,
                            ClassName = "香蕉",
                            Name = "子涵 王"
                        },
                        new
                        {
                            Id = 11,
                            ArtScore = 17,
                            ClassName = "蘋果",
                            Name = "修潔 黎"
                        },
                        new
                        {
                            Id = 12,
                            ArtScore = 47,
                            ClassName = "草莓",
                            Name = "思遠 毛"
                        },
                        new
                        {
                            Id = 13,
                            ArtScore = 38,
                            ClassName = "香蕉",
                            Name = "越彬 劉"
                        },
                        new
                        {
                            Id = 14,
                            ArtScore = 100,
                            ClassName = "草莓",
                            Name = "鴻濤 蘇"
                        },
                        new
                        {
                            Id = 15,
                            ArtScore = 29,
                            ClassName = "草莓",
                            Name = "燁磊 馬"
                        },
                        new
                        {
                            Id = 16,
                            ArtScore = 89,
                            ClassName = "草莓",
                            Name = "明杰 萬"
                        },
                        new
                        {
                            Id = 17,
                            ArtScore = 62,
                            ClassName = "蓮霧",
                            Name = "子騫 秦"
                        },
                        new
                        {
                            Id = 18,
                            ArtScore = 5,
                            ClassName = "蘋果",
                            Name = "雪松 陳"
                        },
                        new
                        {
                            Id = 19,
                            ArtScore = 57,
                            ClassName = "蓮霧",
                            Name = "思淼 潘"
                        },
                        new
                        {
                            Id = 20,
                            ArtScore = 39,
                            ClassName = "草莓",
                            Name = "浩然 蔣"
                        },
                        new
                        {
                            Id = 21,
                            ArtScore = 32,
                            ClassName = "草莓",
                            Name = "博文 白"
                        },
                        new
                        {
                            Id = 22,
                            ArtScore = 36,
                            ClassName = "香蕉",
                            Name = "靖琪 韋"
                        },
                        new
                        {
                            Id = 23,
                            ArtScore = 85,
                            ClassName = "蓮霧",
                            Name = "振家 曾"
                        },
                        new
                        {
                            Id = 24,
                            ArtScore = 23,
                            ClassName = "香蕉",
                            Name = "偉宸 閻"
                        },
                        new
                        {
                            Id = 25,
                            ArtScore = 83,
                            ClassName = "香蕉",
                            Name = "弘文 蘇"
                        },
                        new
                        {
                            Id = 26,
                            ArtScore = 34,
                            ClassName = "蓮霧",
                            Name = "哲瀚 沈"
                        },
                        new
                        {
                            Id = 27,
                            ArtScore = 16,
                            ClassName = "香蕉",
                            Name = "燁霖 趙"
                        },
                        new
                        {
                            Id = 28,
                            ArtScore = 31,
                            ClassName = "草莓",
                            Name = "正豪 何"
                        },
                        new
                        {
                            Id = 29,
                            ArtScore = 36,
                            ClassName = "香蕉",
                            Name = "健雄 方"
                        },
                        new
                        {
                            Id = 30,
                            ArtScore = 53,
                            ClassName = "蘋果",
                            Name = "俊馳 顧"
                        },
                        new
                        {
                            Id = 31,
                            ArtScore = 49,
                            ClassName = "草莓",
                            Name = "偉祺 姚"
                        },
                        new
                        {
                            Id = 32,
                            ArtScore = 96,
                            ClassName = "草莓",
                            Name = "思聰 夏"
                        },
                        new
                        {
                            Id = 33,
                            ArtScore = 18,
                            ClassName = "蓮霧",
                            Name = "黎昕 秦"
                        },
                        new
                        {
                            Id = 34,
                            ArtScore = 48,
                            ClassName = "蘋果",
                            Name = "思聰 汪"
                        },
                        new
                        {
                            Id = 35,
                            ArtScore = 28,
                            ClassName = "草莓",
                            Name = "志澤 劉"
                        },
                        new
                        {
                            Id = 36,
                            ArtScore = 59,
                            ClassName = "草莓",
                            Name = "澤洋 郭"
                        },
                        new
                        {
                            Id = 37,
                            ArtScore = 95,
                            ClassName = "香蕉",
                            Name = "智輝 龍"
                        },
                        new
                        {
                            Id = 38,
                            ArtScore = 7,
                            ClassName = "草莓",
                            Name = "風華 蔡"
                        },
                        new
                        {
                            Id = 39,
                            ArtScore = 73,
                            ClassName = "蓮霧",
                            Name = "嘉懿 侯"
                        },
                        new
                        {
                            Id = 40,
                            ArtScore = 72,
                            ClassName = "香蕉",
                            Name = "樂駒 莫"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
