// <auto-generated />
using KindergartenArtScoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KindergartenArtScoreAPI.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250308150750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("KindergartenArtScoreAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtScore = 89,
                            ClassName = "草莓",
                            Name = "煜城 邵"
                        },
                        new
                        {
                            Id = 2,
                            ArtScore = 52,
                            ClassName = "草莓",
                            Name = "炎彬 姜"
                        },
                        new
                        {
                            Id = 3,
                            ArtScore = 22,
                            ClassName = "香蕉",
                            Name = "博文 何"
                        },
                        new
                        {
                            Id = 4,
                            ArtScore = 26,
                            ClassName = "蘋果",
                            Name = "立輝 蔣"
                        },
                        new
                        {
                            Id = 5,
                            ArtScore = 60,
                            ClassName = "草莓",
                            Name = "懿軒 陶"
                        },
                        new
                        {
                            Id = 6,
                            ArtScore = 65,
                            ClassName = "蘋果",
                            Name = "耀傑 盧"
                        },
                        new
                        {
                            Id = 7,
                            ArtScore = 82,
                            ClassName = "蓮霧",
                            Name = "鷺洋 張"
                        },
                        new
                        {
                            Id = 8,
                            ArtScore = 51,
                            ClassName = "蓮霧",
                            Name = "燁霖 韋"
                        },
                        new
                        {
                            Id = 9,
                            ArtScore = 45,
                            ClassName = "蘋果",
                            Name = "越澤 田"
                        },
                        new
                        {
                            Id = 10,
                            ArtScore = 31,
                            ClassName = "蘋果",
                            Name = "越澤 毛"
                        },
                        new
                        {
                            Id = 11,
                            ArtScore = 69,
                            ClassName = "草莓",
                            Name = "瑞霖 沈"
                        },
                        new
                        {
                            Id = 12,
                            ArtScore = 46,
                            ClassName = "香蕉",
                            Name = "弘文 沈"
                        },
                        new
                        {
                            Id = 13,
                            ArtScore = 87,
                            ClassName = "蓮霧",
                            Name = "語堂 徐"
                        },
                        new
                        {
                            Id = 14,
                            ArtScore = 68,
                            ClassName = "香蕉",
                            Name = "振家 潘"
                        },
                        new
                        {
                            Id = 15,
                            ArtScore = 86,
                            ClassName = "蓮霧",
                            Name = "健柏 於"
                        },
                        new
                        {
                            Id = 16,
                            ArtScore = 82,
                            ClassName = "草莓",
                            Name = "思聰 陶"
                        },
                        new
                        {
                            Id = 17,
                            ArtScore = 10,
                            ClassName = "香蕉",
                            Name = "語堂 程"
                        },
                        new
                        {
                            Id = 18,
                            ArtScore = 45,
                            ClassName = "蘋果",
                            Name = "振家 陳"
                        },
                        new
                        {
                            Id = 19,
                            ArtScore = 86,
                            ClassName = "香蕉",
                            Name = "子默 丁"
                        },
                        new
                        {
                            Id = 20,
                            ArtScore = 56,
                            ClassName = "蘋果",
                            Name = "梓晨 賀"
                        },
                        new
                        {
                            Id = 21,
                            ArtScore = 68,
                            ClassName = "蘋果",
                            Name = "偉誠 洪"
                        },
                        new
                        {
                            Id = 22,
                            ArtScore = 29,
                            ClassName = "草莓",
                            Name = "修潔 邵"
                        },
                        new
                        {
                            Id = 23,
                            ArtScore = 35,
                            ClassName = "香蕉",
                            Name = "紹齊 田"
                        },
                        new
                        {
                            Id = 24,
                            ArtScore = 68,
                            ClassName = "香蕉",
                            Name = "鈺軒 龔"
                        },
                        new
                        {
                            Id = 25,
                            ArtScore = 5,
                            ClassName = "香蕉",
                            Name = "楷瑞 廖"
                        },
                        new
                        {
                            Id = 26,
                            ArtScore = 25,
                            ClassName = "香蕉",
                            Name = "睿淵 蔡"
                        },
                        new
                        {
                            Id = 27,
                            ArtScore = 76,
                            ClassName = "草莓",
                            Name = "志強 許"
                        },
                        new
                        {
                            Id = 28,
                            ArtScore = 18,
                            ClassName = "蘋果",
                            Name = "文軒 譚"
                        },
                        new
                        {
                            Id = 29,
                            ArtScore = 1,
                            ClassName = "草莓",
                            Name = "君浩 鄭"
                        },
                        new
                        {
                            Id = 30,
                            ArtScore = 9,
                            ClassName = "香蕉",
                            Name = "梓晨 朱"
                        },
                        new
                        {
                            Id = 31,
                            ArtScore = 73,
                            ClassName = "蓮霧",
                            Name = "智淵 呂"
                        },
                        new
                        {
                            Id = 32,
                            ArtScore = 17,
                            ClassName = "蘋果",
                            Name = "胤祥 龔"
                        },
                        new
                        {
                            Id = 33,
                            ArtScore = 3,
                            ClassName = "草莓",
                            Name = "弘文 顧"
                        },
                        new
                        {
                            Id = 34,
                            ArtScore = 82,
                            ClassName = "草莓",
                            Name = "瑾瑜 宋"
                        },
                        new
                        {
                            Id = 35,
                            ArtScore = 27,
                            ClassName = "蘋果",
                            Name = "瑾瑜 蘇"
                        },
                        new
                        {
                            Id = 36,
                            ArtScore = 29,
                            ClassName = "香蕉",
                            Name = "曉博 顧"
                        },
                        new
                        {
                            Id = 37,
                            ArtScore = 84,
                            ClassName = "草莓",
                            Name = "俊馳 段"
                        },
                        new
                        {
                            Id = 38,
                            ArtScore = 16,
                            ClassName = "蘋果",
                            Name = "子默 蘇"
                        },
                        new
                        {
                            Id = 39,
                            ArtScore = 18,
                            ClassName = "蓮霧",
                            Name = "遠航 趙"
                        },
                        new
                        {
                            Id = 40,
                            ArtScore = 42,
                            ClassName = "蘋果",
                            Name = "越澤 董"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
